data_dir = "./data"

[local_server]
ip = "127.0.0.1"
port = 8501
id = 1

[[servers]]
ip = "127.0.0.1"
port = 8501
id = 1

[[servers]]
ip = "127.0.0.1"
port = 8502
id = 2

[[servers]]
ip = "127.0.0.1"
port = 8503
id = 3
