data_dir = "./data"
default_queue_num_per_topic = 8
max_segment_size = 100000000 # 100m

[local_server]
ip = "127.0.0.1"
port = 8501
id = 1

[[servers]]
ip = "127.0.0.1"
port = 8501
id = 1

[[servers]]
ip = "127.0.0.1"
port = 8502
id = 2

[[servers]]
ip = "127.0.0.1"
port = 8503
id = 3
