data_dir = "./data"
default_queue_num_per_topic = 8
max_segment_size = 100000000 # 100m
expired_log_check_interval = 86400 # 24h
expired_log_duration = 604800 # 7 day
# 该server属于哪个分片集群，每个分片是leader/followers的raft集群
sharding_id = 1

[zookeeper]
servers = "127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183"
connect_timeout_ms = 500
session_timeout_ms = 5000
retry_count = 3
retry_interval_ms = 1000
base_path = "/distmq"

[local_server]
ip = "127.0.0.1"
port = 8501
id = 1

[[servers]]
ip = "127.0.0.1"
port = 8501
id = 1

[[servers]]
ip = "127.0.0.1"
port = 8502
id = 2

[[servers]]
ip = "127.0.0.1"
port = 8503
id = 3
